### ISSUE TITLE
Chart Title is not styled well

### ISSUE THREAD

**Issue by cendekia** [coroo/chart-js-integration#5]
Hi @coroo,

I tried this awesome chart js for nova package 👍, 
but there is a minor issue, the title is not aligned/styled well.

I'm using nova with default style, here is the screenshot of my stacked chart.

<img width="1415" alt="Screen Shot 2019-12-20 at 17 48 31" src="https://user-images.githubusercontent.com/3895916/71250047-467ad680-2351-11ea-867b-40b08160b697.png">

Is there any way to fix this? Thank you

**Comment by coroo** [comment]
Hi @cendekia , 

Thank you for your interest in this package. 
Im sorry since I use themes, somehow the style is not fit with yours.

I already fix it in v0.0.7 by this [commit](https://github.com/coroo/chart-js-integration/commit/c490d0ad4f061484ce865eee2a97c8bad8006ca0).

So, please update to the [latest version of chart-js-integration package](https://packagist.org/packages/coroowicaksono/chart-js-integration) for solve this issue.
