### ISSUE TITLE
Error after update to v0.0.9

### ISSUE THREAD

**Issue by gmill20** [coroo/chart-js-integration#6]
- Updating coroowicaksono/chart-js-integration (v0.0.6 => v0.0.9): Downloading (100%)

Receive undefined property: stdClass::$fill

p.s
is there anyway to get the charts to show weekly stats as opposed top monthly?

**Comment by coroo** [comment]
Hi @gmill20 , sorry for inconvenience.

I will update in next release (v0.0.10) for this issue. Meanwhile if you need this issue to fix ASAP, please use v0.0.8 by today.

For the weekly basis view, I will make separate issue to create this feature in future. Hopefully we can have this feature in next month.

**Comment by gmill20** [comment]
Brilliant, thanks.

**Comment by coroo** [comment]
Hi @gmill20 , for this issue please update to [v0.0.10](https://packagist.org/packages/coroowicaksono/chart-js-integration#v0.0.10). Again, thank you for informing me about this bug.

For Weekly basis view, please refer to this [issue](https://github.com/coroo/chart-js-integration/issues/7). So that I can close this issue.

**Comment by gmill20** [comment]
This now works for me, issue fixed.

**Comment by gmill20** [comment]
Thanks!

**Comment by coroo** [comment]
> p.s
> is there anyway to get the charts to show weekly stats as opposed top monthly?

Hi @gmill20 , this enhancement already in [v0.0.12](https://github.com/coroo/chart-js-integration/tree/v0.0.12).
For documentation please [see here](https://github.com/coroo/chart-js-integration#use-weekly-view).
